/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ChatImport } from './routes/chat'
import { Route as IndexImport } from './routes/index'
import { Route as UnitsIndexImport } from './routes/units/index'
import { Route as RequestsIndexImport } from './routes/requests/index'
import { Route as PropertiesIndexImport } from './routes/properties/index'
import { Route as InvoicesIndexImport } from './routes/invoices/index'
import { Route as ContactsIndexImport } from './routes/contacts/index'
import { Route as UnitsUnitIdImport } from './routes/units/$unitId'
import { Route as RequestsCreateImport } from './routes/requests/create'
import { Route as RequestsRequestIdImport } from './routes/requests/$requestId'
import { Route as MembersMeImport } from './routes/members/me'
import { Route as ChatChannelIdImport } from './routes/chat/$channelId'

// Create Virtual Routes

const PropertiesCreateLazyImport = createFileRoute('/properties/create')()
const PropertiesPropertyIdLazyImport = createFileRoute(
  '/properties/$propertyId',
)()
const InvoicesCreateLazyImport = createFileRoute('/invoices/create')()
const ContactsCreateLazyImport = createFileRoute('/contacts/create')()
const ContactsContactIdLazyImport = createFileRoute('/contacts/$contactId')()
const AuthSignInLazyImport = createFileRoute('/auth/sign-in')()
const PropertiesPropertyIdCreateUnitLazyImport = createFileRoute(
  '/properties/$propertyId/create-unit',
)()

// Create/Update Routes

const ChatRoute = ChatImport.update({
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UnitsIndexRoute = UnitsIndexImport.update({
  path: '/units/',
  getParentRoute: () => rootRoute,
} as any)

const RequestsIndexRoute = RequestsIndexImport.update({
  path: '/requests/',
  getParentRoute: () => rootRoute,
} as any)

const PropertiesIndexRoute = PropertiesIndexImport.update({
  path: '/properties/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/properties/index.lazy').then((d) => d.Route),
)

const InvoicesIndexRoute = InvoicesIndexImport.update({
  path: '/invoices/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/invoices/index.lazy').then((d) => d.Route),
)

const ContactsIndexRoute = ContactsIndexImport.update({
  path: '/contacts/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contacts/index.lazy').then((d) => d.Route),
)

const PropertiesCreateLazyRoute = PropertiesCreateLazyImport.update({
  path: '/properties/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/properties/create.lazy').then((d) => d.Route),
)

const PropertiesPropertyIdLazyRoute = PropertiesPropertyIdLazyImport.update({
  path: '/properties/$propertyId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/properties/$propertyId.lazy').then((d) => d.Route),
)

const InvoicesCreateLazyRoute = InvoicesCreateLazyImport.update({
  path: '/invoices/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/invoices/create.lazy').then((d) => d.Route),
)

const ContactsCreateLazyRoute = ContactsCreateLazyImport.update({
  path: '/contacts/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contacts/create.lazy').then((d) => d.Route),
)

const ContactsContactIdLazyRoute = ContactsContactIdLazyImport.update({
  path: '/contacts/$contactId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contacts/$contactId.lazy').then((d) => d.Route),
)

const AuthSignInLazyRoute = AuthSignInLazyImport.update({
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/sign-in.lazy').then((d) => d.Route))

const UnitsUnitIdRoute = UnitsUnitIdImport.update({
  path: '/units/$unitId',
  getParentRoute: () => rootRoute,
} as any)

const RequestsCreateRoute = RequestsCreateImport.update({
  path: '/requests/create',
  getParentRoute: () => rootRoute,
} as any)

const RequestsRequestIdRoute = RequestsRequestIdImport.update({
  path: '/requests/$requestId',
  getParentRoute: () => rootRoute,
} as any)

const MembersMeRoute = MembersMeImport.update({
  path: '/members/me',
  getParentRoute: () => rootRoute,
} as any)

const ChatChannelIdRoute = ChatChannelIdImport.update({
  path: '/$channelId',
  getParentRoute: () => ChatRoute,
} as any)

const PropertiesPropertyIdCreateUnitLazyRoute =
  PropertiesPropertyIdCreateUnitLazyImport.update({
    path: '/properties/$propertyId/create-unit',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/properties_/$propertyId/create-unit.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/chat': {
      preLoaderRoute: typeof ChatImport
      parentRoute: typeof rootRoute
    }
    '/chat/$channelId': {
      preLoaderRoute: typeof ChatChannelIdImport
      parentRoute: typeof ChatImport
    }
    '/members/me': {
      preLoaderRoute: typeof MembersMeImport
      parentRoute: typeof rootRoute
    }
    '/requests/$requestId': {
      preLoaderRoute: typeof RequestsRequestIdImport
      parentRoute: typeof rootRoute
    }
    '/requests/create': {
      preLoaderRoute: typeof RequestsCreateImport
      parentRoute: typeof rootRoute
    }
    '/units/$unitId': {
      preLoaderRoute: typeof UnitsUnitIdImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      preLoaderRoute: typeof AuthSignInLazyImport
      parentRoute: typeof rootRoute
    }
    '/contacts/$contactId': {
      preLoaderRoute: typeof ContactsContactIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/contacts/create': {
      preLoaderRoute: typeof ContactsCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/invoices/create': {
      preLoaderRoute: typeof InvoicesCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/properties/$propertyId': {
      preLoaderRoute: typeof PropertiesPropertyIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/properties/create': {
      preLoaderRoute: typeof PropertiesCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/contacts/': {
      preLoaderRoute: typeof ContactsIndexImport
      parentRoute: typeof rootRoute
    }
    '/invoices/': {
      preLoaderRoute: typeof InvoicesIndexImport
      parentRoute: typeof rootRoute
    }
    '/properties/': {
      preLoaderRoute: typeof PropertiesIndexImport
      parentRoute: typeof rootRoute
    }
    '/requests/': {
      preLoaderRoute: typeof RequestsIndexImport
      parentRoute: typeof rootRoute
    }
    '/units/': {
      preLoaderRoute: typeof UnitsIndexImport
      parentRoute: typeof rootRoute
    }
    '/properties/$propertyId/create-unit': {
      preLoaderRoute: typeof PropertiesPropertyIdCreateUnitLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ChatRoute.addChildren([ChatChannelIdRoute]),
  MembersMeRoute,
  RequestsRequestIdRoute,
  RequestsCreateRoute,
  UnitsUnitIdRoute,
  AuthSignInLazyRoute,
  ContactsContactIdLazyRoute,
  ContactsCreateLazyRoute,
  InvoicesCreateLazyRoute,
  PropertiesPropertyIdLazyRoute,
  PropertiesCreateLazyRoute,
  ContactsIndexRoute,
  InvoicesIndexRoute,
  PropertiesIndexRoute,
  RequestsIndexRoute,
  UnitsIndexRoute,
  PropertiesPropertyIdCreateUnitLazyRoute,
])

/* prettier-ignore-end */
