/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ChatImport } from './routes/chat'
import { Route as UnitsIndexImport } from './routes/units/index'
import { Route as RequestsIndexImport } from './routes/requests/index'
import { Route as ManagersIndexImport } from './routes/managers/index'
import { Route as UnitsUnitIdImport } from './routes/units/$unitId'
import { Route as RequestsCreateImport } from './routes/requests/create'
import { Route as RequestsRequestIdImport } from './routes/requests/$requestId'
import { Route as MembersMeImport } from './routes/members/me'
import { Route as ChatChannelIdImport } from './routes/chat/$channelId'
import { Route as ManagersPropertiesIndexImport } from './routes/managers/properties/index'
import { Route as ManagersInvoicesIndexImport } from './routes/managers/invoices/index'
import { Route as ManagersContactsIndexImport } from './routes/managers/contacts/index'
import { Route as ManagersPropertiesPropertyIdCreateUnitImport } from './routes/managers/properties_/$propertyId/create-unit'

// Create Virtual Routes

const AuthSignInLazyImport = createFileRoute('/auth/sign-in')()
const PreviewInvoicesInvoiceIdLazyImport = createFileRoute(
  '/preview/invoices/$invoiceId',
)()
const ManagersUnitsUnitIdLazyImport = createFileRoute(
  '/managers/units/$unitId',
)()
const ManagersPropertiesCreateLazyImport = createFileRoute(
  '/managers/properties/create',
)()
const ManagersPropertiesPropertyIdLazyImport = createFileRoute(
  '/managers/properties/$propertyId',
)()
const ManagersInvoicesCreateLazyImport = createFileRoute(
  '/managers/invoices/create',
)()
const ManagersContactsCreateLazyImport = createFileRoute(
  '/managers/contacts/create',
)()
const ManagersContactsContactIdLazyImport = createFileRoute(
  '/managers/contacts/$contactId',
)()

// Create/Update Routes

const ChatRoute = ChatImport.update({
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const UnitsIndexRoute = UnitsIndexImport.update({
  path: '/units/',
  getParentRoute: () => rootRoute,
} as any)

const RequestsIndexRoute = RequestsIndexImport.update({
  path: '/requests/',
  getParentRoute: () => rootRoute,
} as any)

const ManagersIndexRoute = ManagersIndexImport.update({
  path: '/managers/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInLazyRoute = AuthSignInLazyImport.update({
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/sign-in.lazy').then((d) => d.Route))

const UnitsUnitIdRoute = UnitsUnitIdImport.update({
  path: '/units/$unitId',
  getParentRoute: () => rootRoute,
} as any)

const RequestsCreateRoute = RequestsCreateImport.update({
  path: '/requests/create',
  getParentRoute: () => rootRoute,
} as any)

const RequestsRequestIdRoute = RequestsRequestIdImport.update({
  path: '/requests/$requestId',
  getParentRoute: () => rootRoute,
} as any)

const MembersMeRoute = MembersMeImport.update({
  path: '/members/me',
  getParentRoute: () => rootRoute,
} as any)

const ChatChannelIdRoute = ChatChannelIdImport.update({
  path: '/$channelId',
  getParentRoute: () => ChatRoute,
} as any)

const ManagersPropertiesIndexRoute = ManagersPropertiesIndexImport.update({
  path: '/managers/properties/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/managers/properties/index.lazy').then((d) => d.Route),
)

const ManagersInvoicesIndexRoute = ManagersInvoicesIndexImport.update({
  path: '/managers/invoices/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/managers/invoices/index.lazy').then((d) => d.Route),
)

const ManagersContactsIndexRoute = ManagersContactsIndexImport.update({
  path: '/managers/contacts/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/managers/contacts/index.lazy').then((d) => d.Route),
)

const PreviewInvoicesInvoiceIdLazyRoute =
  PreviewInvoicesInvoiceIdLazyImport.update({
    path: '/preview/invoices/$invoiceId',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/preview/invoices/$invoiceId.lazy').then((d) => d.Route),
  )

const ManagersUnitsUnitIdLazyRoute = ManagersUnitsUnitIdLazyImport.update({
  path: '/managers/units/$unitId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/managers/units/$unitId.lazy').then((d) => d.Route),
)

const ManagersPropertiesCreateLazyRoute =
  ManagersPropertiesCreateLazyImport.update({
    path: '/managers/properties/create',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/managers/properties/create.lazy').then((d) => d.Route),
  )

const ManagersPropertiesPropertyIdLazyRoute =
  ManagersPropertiesPropertyIdLazyImport.update({
    path: '/managers/properties/$propertyId',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/managers/properties/$propertyId.lazy').then(
      (d) => d.Route,
    ),
  )

const ManagersInvoicesCreateLazyRoute = ManagersInvoicesCreateLazyImport.update(
  {
    path: '/managers/invoices/create',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/managers/invoices/create.lazy').then((d) => d.Route),
)

const ManagersContactsCreateLazyRoute = ManagersContactsCreateLazyImport.update(
  {
    path: '/managers/contacts/create',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/managers/contacts/create.lazy').then((d) => d.Route),
)

const ManagersContactsContactIdLazyRoute =
  ManagersContactsContactIdLazyImport.update({
    path: '/managers/contacts/$contactId',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/managers/contacts/$contactId.lazy').then((d) => d.Route),
  )

const ManagersPropertiesPropertyIdCreateUnitRoute =
  ManagersPropertiesPropertyIdCreateUnitImport.update({
    path: '/managers/properties/$propertyId/create-unit',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/managers/properties_/$propertyId/create-unit.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat': {
      preLoaderRoute: typeof ChatImport
      parentRoute: typeof rootRoute
    }
    '/chat/$channelId': {
      preLoaderRoute: typeof ChatChannelIdImport
      parentRoute: typeof ChatImport
    }
    '/members/me': {
      preLoaderRoute: typeof MembersMeImport
      parentRoute: typeof rootRoute
    }
    '/requests/$requestId': {
      preLoaderRoute: typeof RequestsRequestIdImport
      parentRoute: typeof rootRoute
    }
    '/requests/create': {
      preLoaderRoute: typeof RequestsCreateImport
      parentRoute: typeof rootRoute
    }
    '/units/$unitId': {
      preLoaderRoute: typeof UnitsUnitIdImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      preLoaderRoute: typeof AuthSignInLazyImport
      parentRoute: typeof rootRoute
    }
    '/managers/': {
      preLoaderRoute: typeof ManagersIndexImport
      parentRoute: typeof rootRoute
    }
    '/requests/': {
      preLoaderRoute: typeof RequestsIndexImport
      parentRoute: typeof rootRoute
    }
    '/units/': {
      preLoaderRoute: typeof UnitsIndexImport
      parentRoute: typeof rootRoute
    }
    '/managers/contacts/$contactId': {
      preLoaderRoute: typeof ManagersContactsContactIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/managers/contacts/create': {
      preLoaderRoute: typeof ManagersContactsCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/managers/invoices/create': {
      preLoaderRoute: typeof ManagersInvoicesCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/managers/properties/$propertyId': {
      preLoaderRoute: typeof ManagersPropertiesPropertyIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/managers/properties/create': {
      preLoaderRoute: typeof ManagersPropertiesCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/managers/units/$unitId': {
      preLoaderRoute: typeof ManagersUnitsUnitIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/preview/invoices/$invoiceId': {
      preLoaderRoute: typeof PreviewInvoicesInvoiceIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/managers/contacts/': {
      preLoaderRoute: typeof ManagersContactsIndexImport
      parentRoute: typeof rootRoute
    }
    '/managers/invoices/': {
      preLoaderRoute: typeof ManagersInvoicesIndexImport
      parentRoute: typeof rootRoute
    }
    '/managers/properties/': {
      preLoaderRoute: typeof ManagersPropertiesIndexImport
      parentRoute: typeof rootRoute
    }
    '/managers/properties/$propertyId/create-unit': {
      preLoaderRoute: typeof ManagersPropertiesPropertyIdCreateUnitImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  ChatRoute.addChildren([ChatChannelIdRoute]),
  MembersMeRoute,
  RequestsRequestIdRoute,
  RequestsCreateRoute,
  UnitsUnitIdRoute,
  AuthSignInLazyRoute,
  ManagersIndexRoute,
  RequestsIndexRoute,
  UnitsIndexRoute,
  ManagersContactsContactIdLazyRoute,
  ManagersContactsCreateLazyRoute,
  ManagersInvoicesCreateLazyRoute,
  ManagersPropertiesPropertyIdLazyRoute,
  ManagersPropertiesCreateLazyRoute,
  ManagersUnitsUnitIdLazyRoute,
  PreviewInvoicesInvoiceIdLazyRoute,
  ManagersContactsIndexRoute,
  ManagersInvoicesIndexRoute,
  ManagersPropertiesIndexRoute,
  ManagersPropertiesPropertyIdCreateUnitRoute,
])

/* prettier-ignore-end */
