/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ChatImport } from './routes/chat'
import { Route as IndexImport } from './routes/index'
import { Route as UnitsIndexImport } from './routes/units/index'
import { Route as RequestsIndexImport } from './routes/requests/index'
import { Route as PropertiesIndexImport } from './routes/properties/index'
import { Route as InvoicesIndexImport } from './routes/invoices/index'
import { Route as ContactsIndexImport } from './routes/contacts/index'
import { Route as UnitsCreateImport } from './routes/units/create'
import { Route as RequestsCreateImport } from './routes/requests/create'
import { Route as RequestsIdImport } from './routes/requests/$id'
import { Route as PropertiesCreateImport } from './routes/properties/create'
import { Route as MembersMeImport } from './routes/members/me'
import { Route as MembersIdImport } from './routes/members/$id'
import { Route as ChatIdImport } from './routes/chat/$id'
import { Route as UnitsIdIndexImport } from './routes/units/$id/index'
import { Route as PropertiesIdIndexImport } from './routes/properties/$id/index'
import { Route as InvoicesIdIndexImport } from './routes/invoices/$id/index'
import { Route as UnitsIdUpdateImport } from './routes/units/$id/update'
import { Route as PropertiesIdUpdateImport } from './routes/properties/$id/update'
import { Route as PropertiesIdAddUnitImport } from './routes/properties/$id/add-unit'

// Create Virtual Routes

const InvoicesCreateLazyImport = createFileRoute('/invoices/create')()
const ContactsCreateLazyImport = createFileRoute('/contacts/create')()
const ContactsContactIdLazyImport = createFileRoute('/contacts/$contactId')()
const AuthSignInLazyImport = createFileRoute('/auth/sign-in')()

// Create/Update Routes

const ChatRoute = ChatImport.update({
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UnitsIndexRoute = UnitsIndexImport.update({
  path: '/units/',
  getParentRoute: () => rootRoute,
} as any)

const RequestsIndexRoute = RequestsIndexImport.update({
  path: '/requests/',
  getParentRoute: () => rootRoute,
} as any)

const PropertiesIndexRoute = PropertiesIndexImport.update({
  path: '/properties/',
  getParentRoute: () => rootRoute,
} as any)

const InvoicesIndexRoute = InvoicesIndexImport.update({
  path: '/invoices/',
  getParentRoute: () => rootRoute,
} as any)

const ContactsIndexRoute = ContactsIndexImport.update({
  path: '/contacts/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contacts/index.lazy').then((d) => d.Route),
)

const InvoicesCreateLazyRoute = InvoicesCreateLazyImport.update({
  path: '/invoices/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/invoices/create.lazy').then((d) => d.Route),
)

const ContactsCreateLazyRoute = ContactsCreateLazyImport.update({
  path: '/contacts/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contacts/create.lazy').then((d) => d.Route),
)

const ContactsContactIdLazyRoute = ContactsContactIdLazyImport.update({
  path: '/contacts/$contactId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contacts/$contactId.lazy').then((d) => d.Route),
)

const AuthSignInLazyRoute = AuthSignInLazyImport.update({
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/sign-in.lazy').then((d) => d.Route))

const UnitsCreateRoute = UnitsCreateImport.update({
  path: '/units/create',
  getParentRoute: () => rootRoute,
} as any)

const RequestsCreateRoute = RequestsCreateImport.update({
  path: '/requests/create',
  getParentRoute: () => rootRoute,
} as any)

const RequestsIdRoute = RequestsIdImport.update({
  path: '/requests/$id',
  getParentRoute: () => rootRoute,
} as any)

const PropertiesCreateRoute = PropertiesCreateImport.update({
  path: '/properties/create',
  getParentRoute: () => rootRoute,
} as any)

const MembersMeRoute = MembersMeImport.update({
  path: '/members/me',
  getParentRoute: () => rootRoute,
} as any)

const MembersIdRoute = MembersIdImport.update({
  path: '/members/$id',
  getParentRoute: () => rootRoute,
} as any)

const ChatIdRoute = ChatIdImport.update({
  path: '/$id',
  getParentRoute: () => ChatRoute,
} as any)

const UnitsIdIndexRoute = UnitsIdIndexImport.update({
  path: '/units/$id/',
  getParentRoute: () => rootRoute,
} as any)

const PropertiesIdIndexRoute = PropertiesIdIndexImport.update({
  path: '/properties/$id/',
  getParentRoute: () => rootRoute,
} as any)

const InvoicesIdIndexRoute = InvoicesIdIndexImport.update({
  path: '/invoices/$id/',
  getParentRoute: () => rootRoute,
} as any)

const UnitsIdUpdateRoute = UnitsIdUpdateImport.update({
  path: '/units/$id/update',
  getParentRoute: () => rootRoute,
} as any)

const PropertiesIdUpdateRoute = PropertiesIdUpdateImport.update({
  path: '/properties/$id/update',
  getParentRoute: () => rootRoute,
} as any)

const PropertiesIdAddUnitRoute = PropertiesIdAddUnitImport.update({
  path: '/properties/$id/add-unit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/chat': {
      preLoaderRoute: typeof ChatImport
      parentRoute: typeof rootRoute
    }
    '/chat/$id': {
      preLoaderRoute: typeof ChatIdImport
      parentRoute: typeof ChatImport
    }
    '/members/$id': {
      preLoaderRoute: typeof MembersIdImport
      parentRoute: typeof rootRoute
    }
    '/members/me': {
      preLoaderRoute: typeof MembersMeImport
      parentRoute: typeof rootRoute
    }
    '/properties/create': {
      preLoaderRoute: typeof PropertiesCreateImport
      parentRoute: typeof rootRoute
    }
    '/requests/$id': {
      preLoaderRoute: typeof RequestsIdImport
      parentRoute: typeof rootRoute
    }
    '/requests/create': {
      preLoaderRoute: typeof RequestsCreateImport
      parentRoute: typeof rootRoute
    }
    '/units/create': {
      preLoaderRoute: typeof UnitsCreateImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      preLoaderRoute: typeof AuthSignInLazyImport
      parentRoute: typeof rootRoute
    }
    '/contacts/$contactId': {
      preLoaderRoute: typeof ContactsContactIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/contacts/create': {
      preLoaderRoute: typeof ContactsCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/invoices/create': {
      preLoaderRoute: typeof InvoicesCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/contacts/': {
      preLoaderRoute: typeof ContactsIndexImport
      parentRoute: typeof rootRoute
    }
    '/invoices/': {
      preLoaderRoute: typeof InvoicesIndexImport
      parentRoute: typeof rootRoute
    }
    '/properties/': {
      preLoaderRoute: typeof PropertiesIndexImport
      parentRoute: typeof rootRoute
    }
    '/requests/': {
      preLoaderRoute: typeof RequestsIndexImport
      parentRoute: typeof rootRoute
    }
    '/units/': {
      preLoaderRoute: typeof UnitsIndexImport
      parentRoute: typeof rootRoute
    }
    '/properties/$id/add-unit': {
      preLoaderRoute: typeof PropertiesIdAddUnitImport
      parentRoute: typeof rootRoute
    }
    '/properties/$id/update': {
      preLoaderRoute: typeof PropertiesIdUpdateImport
      parentRoute: typeof rootRoute
    }
    '/units/$id/update': {
      preLoaderRoute: typeof UnitsIdUpdateImport
      parentRoute: typeof rootRoute
    }
    '/invoices/$id/': {
      preLoaderRoute: typeof InvoicesIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/properties/$id/': {
      preLoaderRoute: typeof PropertiesIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/units/$id/': {
      preLoaderRoute: typeof UnitsIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ChatRoute.addChildren([ChatIdRoute]),
  MembersIdRoute,
  MembersMeRoute,
  PropertiesCreateRoute,
  RequestsIdRoute,
  RequestsCreateRoute,
  UnitsCreateRoute,
  AuthSignInLazyRoute,
  ContactsContactIdLazyRoute,
  ContactsCreateLazyRoute,
  InvoicesCreateLazyRoute,
  ContactsIndexRoute,
  InvoicesIndexRoute,
  PropertiesIndexRoute,
  RequestsIndexRoute,
  UnitsIndexRoute,
  PropertiesIdAddUnitRoute,
  PropertiesIdUpdateRoute,
  UnitsIdUpdateRoute,
  InvoicesIdIndexRoute,
  PropertiesIdIndexRoute,
  UnitsIdIndexRoute,
])

/* prettier-ignore-end */
